package edu.utap.gymfree.ui.chat

import com.google.firebase.Timestamp
import com.google.firebase.firestore.ServerTimestamp

// Firebase demands an empty constructor, so all fields must be optional
data class ChatRow(
    var name: String? = null,
    var message: String? = null,
    var ownerUid: String? = null,
    var receiverUid: String? = null,
    var receiverName: String? = null,
    var pictureUUID: String? = null,
    var memberUid: String? = null,
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // rowID is generated by firestore, used as primary key
    var rowID: String = ""
)
