package edu.utap.gymfree.ui.book

import com.google.firebase.Timestamp
import com.google.firebase.firestore.ServerTimestamp

// Firebase demands an empty constructor, so all fields must be optional
data class Timeslot(

    var endTime: String? = null,
    var startTime: String? = null,
//    @ServerTimestamp val timeStamp: Timestamp? = null,
    // rowID is generated by firestore, used as primary key
    var rowID: String = ""
)
