package edu.utap.gymfree

import com.google.firebase.Timestamp
import com.google.firebase.firestore.ServerTimestamp

data class Location(
    var name: String? = null,
    var address: String? = null,
    var ownerUid: String? = null,
    var pictureUUID: String? = null,
    var capacity: Number? = null,
    var openingTime: Number? = null,
    var closingTime: Number? = null,
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // rowID is generated by firestore, used as primary key
    var rowID: String = ""
)