package edu.utap.gymfree

import com.google.firebase.Timestamp
import com.google.firebase.firestore.ServerTimestamp

data class Reservation(
    var address: String? = null,
    var ownerUid: String? = null,
    var pictureUUID: String? = null,
    var capacity: Float? = null,
    var openingTime: Float? = null,
    var closingTime: Float? = null,
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // rowID is generated by firestore, used as primary key
    var rowID: String = ""
)