package edu.utap.gymfree

import com.google.firebase.Timestamp
import com.google.firebase.firestore.ServerTimestamp

data class Reservation(
    var name: String? = null,
    var userId: String? = null,
    var startTime: String? = null,
    var endTime: String? = null,
    var timeslotId: String? = null,
    var locationId: String? = null,
//    @ServerTimestamp val timeStamp: Timestamp? = null,
    // rowID is generated by firestore, used as primary key
    var rowId: String = ""
)
